[workspace]
members = ["examples/with_leptos", "crates/*"]
default-members = ["examples/with_leptos", "crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
clap = "4"
colorsys = "0.6"
console_error_panic_hook = "0.1"
console_log = "1.0.0"
dashmap = "5"
derivative = "2"
enum-ordinalize = "3"
heck = "0.4"
indexmap = "1"
insta = "1"
lazy_static = "1"
leptos = "0.2"
lightningcss = "1.0.0-alpha.40"
log = "0.4"
napi = "2"
napi-build = "2"
napi-derive = "2"
owo-colors = "*"
parcel_sourcemap = "2"
readonly = "0.2"
regex = "1"
serde = "1"
serde_json = "1"
thiserror = "1"
typed-builder = "0.14.0"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"

skribble = { path = "./crates/skribble", version = "0.0.0" }
skribble_core = { path = "./crates/skribble_core", version = "0.0.0" }
skribble_plugin_rust = { path = "./crates/skribble_plugin_rust", version = "0.0.0" }
skribble_preset_default = { path = "./crates/skribble_preset_default", version = "0.0.0" }

[profile.release.package.skribble]
opt-level = "s"

[workspace.package]
version = "0.0.0"
homepage = "https://github.com/ifiokjr/skribble"
repository = "https://github.com/ifiokjr/skribble"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"
license = "Unlicense"
