[workspace]
members = ["examples/with_leptos", "crates/*"]
default-members = ["examples/with_leptos", "crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
clap = "4"
console_error_panic_hook = "0.1"
console_log = "1"
darling = "0.14"
dashmap = "5"
derivative = "2"
enum-ordinalize = "3"
globset = "0.4"
heck = "0.4"
indent_write = "2"
indexmap = "1"
indoc = "2"
insta = "1"
itertools = "0.10"
lazy_static = "1"
leptos = "0.2"
lightningcss = "1.0.0-alpha.40"
log = "0.4"
napi = "2"
napi-build = "2"
napi-derive = "2"
owo-colors = "3"
palette = "0.6"
parcel_sourcemap = "2"
quote = "1"
readonly = "0.2"
regex = "1"
"rkyv" = "0.7"
serde = "1"
serde_json = "1"
syn = "2"
thiserror = "1"
typed-builder = "0.14"
walkdir = "2"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"

# Internal crates
skribble = { path = "./crates/skribble", version = "0.0.0" }
skribble_client = { path = "./crates/skribble_client", version = "0.0.0" }
skribble_core = { path = "./crates/skribble_core", version = "0.0.0" }
skribble_plugin_rust = { path = "./crates/skribble_plugin_rust", version = "0.0.0" }
skribble_preset_default = { path = "./crates/skribble_preset_default", version = "0.0.0" }

[workspace.package]
version = "0.0.0"
homepage = "https://github.com/ifiokjr/skribble"
repository = "https://github.com/ifiokjr/skribble"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"
license = "Unlicense"
rust-version = "1.68.0"
categories = ["web-programming", "wasm"]

[profile.release.package.skribble]
opt-level = "s"
