[workspace]
members = ["examples/with_leptos", "crates/*"]
default-members = ["examples/with_leptos", "crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
clap = "4"
colorsys = "0.6"
console_error_panic_hook = "0.1"
console_log = "0.2"
dashmap = "5"
enum-ordinalize = "3"
heck = "0.4"
indexmap = "1"
insta = "1"
lazy_static = "1"
leptos = "0.1"
lightningcss = "1.0.0-alpha.39"
log = "0.4"
napi = "2"
napi-build = "2"
napi-derive = "2"
owo-colors = "*"
parcel_sourcemap = "2"
readonly = "0.2"
regex = "1"
serde = "1"
serde_json = "1"
thiserror = "1"
typed-builder = "0.11"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"

skribble = { path = "./crates/skribble" }
skribble_core = { path = "./crates/skribble_core" }

[profile.release.package.skribble]
opt-level = "s"
