[workspace]
members = ["crates/*"]
default-members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
derivative = "2"
globset = "0.4"
heck = "0.4"
indent_write = "2"
indexmap = "1"
indoc = "2"
insta = "1"
lazy_static = "1"
lightningcss = "1.0.0-alpha.40"
palette = "0.6"
readonly = "0.2"
regex = "1"
serde = "1"
serde_json = "1"
syn = "2"
thiserror = "1"
typed-builder = "0.14"
walkdir = "2"

# Internal crates
skribble = { path = "./crates/skribble", version = "0.0.0" }
skribble_color = { path = "./crates/skribble_color", version = "0.0.0" }
skribble_core = { path = "./crates/skribble_core", version = "0.0.0" }
skribble_plugin_rust = { path = "./crates/skribble_plugin_rust", version = "0.0.0" }
skribble_preset_default = { path = "./crates/skribble_preset_default", version = "0.0.0" }

[workspace.package]
version = "0.0.0"
homepage = "https://github.com/ifiokjr/skribble"
repository = "https://github.com/ifiokjr/skribble"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
edition = "2021"
license = "Unlicense"
rust-version = "1.68.0"
categories = ["web-programming", "wasm"]

[profile.release.package.skribble]
opt-level = "s"
