[package]
name = "skribble_core"
version = "0.0.0"
authors = ["Ifiok Jr. <ifiokotung@gmail.com>"]
documentation = "https://docs.rs/skribble_core"
edition = "2021"
homepage = "https://github.com/ifiokjr/skribble"
include = ["src/**/*.rs", "Cargo.toml", "readme.md"]
keywords = ["build", "atomic", "css"]
license = "Unlicense"
readme = "readme.md"
repository = "https://github.com/ifiokjr/skribble"
description = "Core features for the skribble atomic css library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorsys = { workspace = true }
enum-ordinalize = { workspace = true }
heck = { workspace = true }
indexmap = { features = ["serde-1"], workspace = true }
lazy_static = { workspace = true }
lightningcss = { workspace = true }
parcel_sourcemap = { workspace = true }
readonly = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
insta = { features = ["json"], workspace = true }
