name: "ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, 1.69.0, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup development environment
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
          rust: ${{ matrix.rust }}

      - name: cache rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}

      - name: build
        run: build:all
        shell: bash

      - name: lint
        run: lint:all
        shell: bash

      - name: test
        run: test:all
        shell: bash
