name: "ci"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: install devenv.sh
        run: nix profile install github:cachix/devenv/v0.5
        shell: sh
      - run: devenv ci
      - run: devenv shell echo ok

